### ISSUE TITLE
DSB Item - Energy standards consultations

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/future-plan#45]
A series of consultations have been pulished as placeholders and will be progressively developed over this quarter with a view to completing the Energy standards to candidate level by October/November

**Comment by CDR-API-Stream** [comment]
This work is progressing well. Decision proposals have now been created for consultation:

* [Decision Proposal 190 - Candidate Generic Tariff End Points](https://github.com/ConsumerDataStandardsAustralia/standards/issues/190)
* [Decision Proposal 196 - Candidate DER End Points](https://github.com/ConsumerDataStandardsAustralia/standards/issues/196)
* [Decision Proposal 195 - Candidate Usage End Points](https://github.com/ConsumerDataStandardsAustralia/standards/issues/195)
* [Decision Proposal 194 - Candidate NMI Standing Data End Points](https://github.com/ConsumerDataStandardsAustralia/standards/issues/194)
* [Decision Proposal 193 - Energy Non-functional Requirements](https://github.com/ConsumerDataStandardsAustralia/standards/issues/193)

Since consultation is ongoing this work has been moved to Q4 of the Future Plan.

**Comment by CDR-API-Stream** [comment]
These consultations are now complete or underway

**Comment by CDR-API-Stream** [comment]
All of the candidate energy consultations are complete with the outcomes documented in v1.14.0 of the standards
