### ISSUE TITLE
DSB Item - CX Standards - Joint Accounts DP162

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/future-plan#56]
# Problem Statement

[Decision proposal 162](https://github.com/ConsumerDataStandardsAustralia/standards/issues/162) relates to CX Standards for joint accounts.

Data standards have been identified in relation to several areas, including for:
- Joint account notifications
- Notification alerts
- Vulnerable joint account holders
- Pending disclosures
- Ceasing joint account data sharing

Elements of this decision proposal have been consulted on extensively throughout 2020 and 2021. This decision proposal has been informed by the following:
- Noting Paper 207 consultation
- Noting Paper 157 consultation
- Draft v3 Rules consultation
- Design Paper: an opt-out data sharing model
- Public joint accounts workshop in March 2021. See public workshop Miro Board
- Phase 3 CX research – Rounds 1, 2, 3 and, 6
- Consumer Policy Research Centre (CPRC) report: Joint accounts & the Consumer Data Right

Feedback is now open for this proposal and will close on Tuesday 30 November 2021.

**Comment by CatrinaM** [comment]
DP 162 -  HI please find attached our feedback on your Notification settings.  Please let me know if you have any further questions or need to clarify anything
thanks
Catrina

1.1 JAH-A amends notifications

1. Indications are that the notifications are at account level rather than customer level - this mean that a customer may receive 10 notifications on their joint accounts (if they have split loans) for data sharing preferences.  This feels like it should sit at customer level rather than account level - can you advise if this is the intention?
2. Granular level of notifications being event based, seems like overkill to us (but may work for bigger banks who have the capability)
3. Option 3  Granular control - does not seem to meet the rule that we MUST notify of the changes on their accounts (feels contradictory to the rule 4A.16 (3)
4. Option 2 Notification frequency- specify "should" however the rules again specify MUST, therefore feels contradictory
5. Option 5 + Confirmation screen- Consequences of amending the schedule - this is a must to notify, however, option 2 is should - therefore again feels contradictory to the rule.

1.2 JAH A = Amends notifications:

Option 6 - Means to Amend - Please confirm what the is required in relation to this - is there a requirement to provide a notification schedule for every event type to be switched on or off, or just to be able to turn off all notification types?  the rule does not specify that the granular level of event type is a must

Option 3- Do we have to comply with granular control on joint account notification types?

Option 2 Notifications - the rule states that must provide alternative notification schedules including reducing the summary (4A.14) yet option 2 states "should" - can you confirm if ON and OFF are sufficient notification frequencies?, or if we have to provide another frequency type other than on/off?
If no to above; 
Option 9 - why is ON or OFF not sufficient in terms of the frequency options

General question:
1. Is it OK to use first names on DOMS dashboard and notifications (as an example "Jon has stopped sharing his data") or should we remain generic to account holder 1, 2 etc?
2. Our assumption is that the CDR Notifications for Joint Accounts are to be delivered via electronic means only (Email/SMS NOT Paper)  Could you please confirm that this is correct?

**Comment by CDR-CX-Stream** [comment]
Hi @CatrinaM - the consultation for DP162 is being conducted here: https://github.com/ConsumerDataStandardsAustralia/standards/issues/162

This post relates to an item on our quarterly plan, but is not the consultation itself.

If this is a question relating to the joint accounts consultation, could you please post it in [DP162](https://github.com/ConsumerDataStandardsAustralia/standards/issues/162)? We can respond to your questions there, which will benefit the community and will also mean your post counts towards the consultation.

Alternatively, we can copy your post to DP162 and attribute it to you if you'd prefer that.
